from __future__ import annotations

# Editorially reviewed international versions of the eight search-intent guides
# introduced in v3.7.49. Related-guide slugs are inherited from the English
# source in app.seo_content so every language keeps the same topic graph.

INTERNATIONAL_GUIDES = {
    "fr": {
        "alibaba-dispute-closed-no-refund": {
            "title": "Alibaba a clôturé le litige sans remboursement : points à vérifier",
            "description": "Liste de contrôle pour analyser une décision Alibaba, les preuves manquantes, les délais et les voies de recours encore possibles.",
            "intro": "La clôture d’un litige ne dit pas, à elle seule, si les preuves étaient insuffisantes, si la demande était incohérente, si un délai a été dépassé ou si une autre procédure reste ouverte.",
            "summary": "Conservez le dossier complet, identifiez la décision exacte et la règle citée, puis comparez les preuves déposées au problème et au remboursement demandé.",
            "sections": [
                ("Conservez l’intégralité du dossier", ["Téléchargez la demande, la réponse du vendeur, les questions de la plateforme, la liste des pièces, les changements de statut, la décision et la date de clôture.", "Gardez la page de commande ainsi que la version des conditions Trade Assurance ou autres règles applicables à la transaction."]),
                ("Lisez le motif indiqué", ["Distinguez une clôture procédurale, un problème de délai, une insuffisance de preuves et un rejet sur le fond.", "Ne supposez pas que la décision a traité un argument qui n’avait jamais été formulé clairement ni documenté."]),
                ("Auditez votre propre dossier", ["Vérifiez que les dates, montants, mesure demandée et motif principal sont restés cohérents pendant toutes les étapes du litige.", "Reliez chaque affirmation importante à un fichier précis et notez les pièces demandées par Alibaba mais non reçues ou non examinées."]),
                ("Recensez les options restantes", ["Vérifiez si un réexamen, appel, réclamation, litige de paiement, assureur, mise en demeure, médiation, arbitrage ou tribunal reste accessible.", "Les délais et la compétence dépendent du contrat, de l’entité, du moyen de paiement et du pays ; ne vous fiez pas à un délai générique trouvé en ligne."]),
            ],
            "mistakes": ["Supprimer les pages du litige clôturé", "Présenter une nouvelle version des faits sans preuves", "Confondre une décision de plateforme avec un jugement", "Laisser expirer un délai bancaire ou contractuel en attendant le support"],
            "faq": [("Un litige Alibaba clôturé peut-il être rouvert ?", "Cela dépend du statut, de la procédure actuelle et de nouvelles preuves éventuelles. Conservez le dossier et vérifiez les options affichées dans le compte."), ("La clôture signifie-t-elle que le fournisseur avait raison ?", "Pas nécessairement. Un dossier peut être clos pour des raisons de procédure ou de preuve. Lisez le texte exact et l’historique."), ("Que doit contenir une demande de réexamen ?", "Une chronologie concise, l’erreur précise invoquée, les preuves qui l’établissent et un résultat demandé clairement.")],
        },
        "customs-clearance-problem": {
            "title": "Marchandises chinoises bloquées en douane : liste de contrôle du litige",
            "description": "Comment organiser les preuves lorsque la douane retarde ou refuse des marchandises en raison de factures, classement, certificats ou marquages.",
            "intro": "Un problème douanier n’est pas automatiquement une faute du fournisseur. Identifiez d’abord le motif officiel, l’importateur déclaré, l’Incoterm et la partie qui avait promis chaque document ou obligation de conformité.",
            "summary": "Commencez par l’avis écrit de la douane, puis reliez chaque élément manquant ou incorrect au contrat, aux documents de transport et à la partie responsable.",
            "sections": [
                ("Obtenez le motif officiel", ["Demandez l’avis de la douane, du transitaire, du transporteur ou de l’autorité indiquant ce qui manque, est incohérent, interdit ou en cours d’examen.", "Distinguez une simple demande de document d’une retenue, saisie, interdiction, réexpédition ou destruction possible."]),
                ("Répartissez les responsabilités", ["Vérifiez l’Incoterm, l’importateur déclaré, les instructions au déclarant et les promesses contractuelles concernant classement, origine, valeur, certificats et marquages.", "Ne supposez pas que la formule « porte à porte » transfère toutes les obligations légales sans lire l’accord écrit."]),
                ("Conservez toute la chaîne documentaire", ["Gardez facture commerciale, liste de colisage, connaissement ou lettre de transport aérien, code SH, documents d’origine, certificats, déclarations et instructions du fournisseur.", "Archivez chaque version corrigée et l’identité de son émetteur afin de préserver la piste d’audit."]),
                ("Maîtrisez les coûts et les délais", ["Suivez les frais et délais de stockage, surestaries, courtage, essais, retour ou destruction avec factures et avis à l’appui.", "Avant de payer un nouveau montant demandé par le fournisseur, vérifiez le bénéficiaire et obtenez une explication écrite de ce que ce paiement résout."]),
            ],
            "mistakes": ["Se fier uniquement au résumé du fournisseur", "Modifier une facture sans conserver l’original", "Ignorer les délais de stockage ou d’abandon", "Imputer automatiquement le problème au fournisseur sans vérifier l’Incoterm"],
            "faq": [("Qui est responsable lorsque la douane bloque la marchandise ?", "Cela dépend du motif officiel, du droit de l’importation, du rôle de l’importateur, de l’Incoterm et des promesses contractuelles."), ("Le fournisseur doit-il émettre une nouvelle facture ?", "Seulement pour corriger une erreur réelle. Conservez l’original et n’utilisez jamais de valeur ou description fausse."), ("Peut-on réclamer les frais douaniers au fournisseur ?", "Éventuellement, si une violation documentée du fournisseur les a causés et si le contrat ou le droit applicable permet leur récupération.")],
        },
        "damaged-or-short-shipment": {
            "title": "Marchandises chinoises endommagées ou manquantes : prouver la réclamation",
            "description": "Preuves à réunir pour cartons endommagés, produits cassés, unités manquantes, quantité insuffisante ou livraison incomplète.",
            "intro": "Les dossiers de dommage et de quantité manquante reposent fortement sur les preuves créées à la réception. Photographiez l’état fermé, les étiquettes, le comptage et les documents du transporteur avant de reconditionner ou distribuer les produits.",
            "summary": "Montrez la quantité convenue, la quantité reçue, l’état à l’arrivée, la méthode de contrôle et l’effet financier du dommage ou du manque.",
            "sections": [
                ("Documentez l’état à l’arrivée", ["Photographiez le conteneur, la palette ou les cartons avant ouverture, notamment scellés, étiquettes, bosses, humidité et dommages visibles.", "Conservez les bons de livraison et inscrivez toute réserve ou remarque de dommage auprès du transporteur."]),
                ("Comptez et échantillonnez méthodiquement", ["Utilisez une feuille de comptage mentionnant numéros de cartons, références, lots et personne ayant effectué le contrôle.", "Pour les dommages, indiquez le nombre d’unités inspectées, le nombre d’échecs et la méthode de sélection de l’échantillon."]),
                ("Séparez transport et fournisseur", ["Comparez les obligations d’emballage, les Incoterms, les documents de transport et le moment où les risques ont été transférés.", "Ne supposez pas que toute perte de transport relève du fournisseur ni que tout défaut d’emballage relève du transporteur."]),
                ("Calculez une demande justifiée", ["Reliez chaque unité manquante ou endommagée à son prix facturé et aux coûts documentés de contrôle, réparation ou destruction.", "Conservez les marchandises et l’emballage jusqu’à ce que les parties confirment si une expertise est nécessaire."]),
            ],
            "mistakes": ["Signer un bon sans réserve malgré un dommage visible", "Jeter l’emballage avant expertise", "Déclarer toute la commande défectueuse après une seule unité contrôlée", "Demander une somme globale sans calcul"],
            "faq": [("Faut-il ouvrir tous les cartons ?", "Utilisez un plan d’inspection défendable et consignez ce qui a été contrôlé. L’étendue dépend de la cargaison et de la procédure."), ("Qui répond des dommages de transport ?", "Le contrat, les Incoterms, les documents du transporteur, les obligations d’emballage et la cause réelle sont déterminants."), ("Un rapport d’entrepôt est-il utile ?", "Oui, surtout s’il indique heure de réception, état des scellés, nombre de cartons, photos et méthode d’inspection.")],
        },
        "order-not-delivered-tracking-problem": {
            "title": "Commande chinoise non livrée : suivi et preuves à conserver",
            "description": "Que collecter lorsque le suivi est invalide, bloqué, livré au mauvais endroit ou indique une livraison jamais reçue.",
            "intro": "Une non-livraison après expédition diffère d’une absence d’expédition. Établissez une chronologie au niveau des transporteurs et identifiez l’itinéraire, le destinataire, le scan de livraison et chaque anomalie.",
            "summary": "Conservez l’adresse convenue, les données du transporteur, l’historique de suivi, la preuve de livraison, les échanges et le point où l’envoi s’est arrêté ou a été mal livré.",
            "sections": [
                ("Capturez tout l’historique de suivi", ["Conservez le nom du transporteur, le numéro complet et tous les scans datés, pas seulement le dernier statut.", "Vérifiez le numéro sur le système officiel et notez toute incohérence d’adresse, de poids ou de service."]),
                ("Demandez la preuve de livraison", ["Demandez adresse de livraison, nom du destinataire, signature, photo, GPS ou dossier du transporteur local lorsqu’ils existent.", "Un statut générique « livré » ne prouve pas que le bon destinataire a reçu les marchandises."]),
                ("Retracez les transferts", ["Identifiez transitaires, consolidateurs, déclarants et transporteurs du dernier kilomètre, y compris chaque nouveau numéro de suivi.", "Notez le moment du transfert des risques et responsabilités selon le contrat et l’Incoterm."]),
                ("Avertissez les bonnes parties", ["Informez rapidement et par écrit le vendeur, la plateforme, le transporteur, l’assureur et le prestataire de paiement lorsque cela s’applique.", "Conservez les références de réclamation et ne jetez pas emballages ou documents d’une livraison partielle."]),
            ],
            "mistakes": ["Montrer un suivi sans nom de transporteur", "Laisser expirer le délai de réclamation du transporteur", "Confondre livraison à un entrepôt intermédiaire et livraison à l’acheteur", "Ne pas conserver les numéros de suivi de remplacement"],
            "faq": [("Le suivi indique livré mais rien n’est arrivé : que faire ?", "Demandez une preuve détaillée et comparez adresse, destinataire, poids et dossier local avec la commande."), ("Le vendeur est-il toujours responsable d’une perte en transit ?", "Non. Le contrat, les Incoterms, l’assurance et le lieu de la perte comptent."), ("Que faire si le numéro de suivi semble faux ?", "Conservez la réponse officielle du transporteur, les incohérences et les messages du fournisseur, sans tirer de conclusion au-delà des preuves.")],
        },
        "supplier-certificate-problem": {
            "title": "Certificat chinois erroné ou invalide : contrôles à effectuer",
            "description": "Liste de preuves lorsqu’un certificat manque, concerne un autre produit, est invérifiable, expiré ou inadapté au marché de destination.",
            "intro": "Un logo ou un PDF intitulé « certificat » ne suffit pas. Il faut déterminer le document promis, son émetteur, le produit et la norme couverts, ainsi que sa validité pour le marché visé.",
            "summary": "Comparez le document promis à l’émetteur réel, au numéro, au modèle, à la norme, au champ d’application, aux dates et aux exigences du pays de destination.",
            "sections": [
                ("Conservez ce qui avait été promis", ["Gardez messages, devis et clause de commande indiquant le certificat, rapport d’essai, déclaration ou enregistrement que le fournisseur devait fournir.", "Notez si ce document conditionnait le paiement, la validation de production, l’expédition ou l’importation."]),
                ("Vérifiez le document", ["Contrôlez coordonnées de l’émetteur, numéro, modèle, demandeur, fabricant, norme, dates d’émission et d’expiration et base publique éventuelle.", "Lorsque l’enjeu le justifie, contactez l’émetteur par des coordonnées obtenues indépendamment."]),
                ("Distinguez les types de documents", ["Rapport d’essai, certificat, déclaration de conformité, audit d’usine et enregistrement produit ne sont pas interchangeables.", "N’affirmez pas qu’un document est falsifié sans preuve fiable ; décrivez l’incohérence précise ou l’échec de vérification."]),
                ("Reliez le défaut à la transaction", ["Expliquez pourquoi le document manquant ou inadapté empêche l’importation, la vente, l’installation ou l’utilisation convenue.", "Conservez les échanges avec douane, laboratoire, consultant ou autorité qui identifient le problème."]),
            ],
            "mistakes": ["Accepter un certificat d’un autre modèle ou fabricant", "Se fier uniquement à un lien fourni par le vendeur", "Confondre rapport d’essai et autorisation de mise sur le marché", "Accuser de falsification avant vérification"],
            "faq": [("Comment vérifier un certificat ?", "Contrôlez indépendamment l’émetteur, le numéro, le champ, le modèle et les dates. Les exigences varient selon le produit et le pays."), ("Le logo CE prouve-t-il la conformité ?", "Non. Le marquage seul ne prouve pas que toutes les obligations et tous les documents applicables sont satisfaits."), ("Cela peut-il justifier une annulation ou un remboursement ?", "Oui, éventuellement, si le document était une condition convenue ou si le produit ne peut pas être utilisé légalement comme prévu.")],
        },
        "supplier-disappeared-after-payment": {
            "title": "Fournisseur chinois disparu après paiement : premières démarches",
            "description": "Preuves à préserver et délais à vérifier lorsqu’un fournisseur chinois ne répond plus après un acompte ou le paiement intégral.",
            "intro": "Le silence après paiement peut avoir plusieurs causes, mais la priorité reste la même : préserver les preuves de la transaction, de l’identité et des échanges avant que les comptes ou pages ne changent.",
            "summary": "Notez qui a reçu l’argent, ce qui avait été promis, le dernier événement de production ou d’expédition confirmé et chaque tentative de contact restée sans réponse.",
            "sections": [
                ("Préservez identité et transaction", ["Gardez raison sociale, informations d’enregistrement, profil Alibaba ou marketplace, site, adresses, bénéficiaire bancaire et facture.", "Exportez la conversation complète si possible avec dates, noms, pièces jointes et contexte des messages vocaux."]),
                ("Vérifiez les changements de compte", ["Documentez annonces supprimées, changement de nom, compte bloqué, courriels rejetés et téléphones déconnectés.", "Ne vous limitez pas aux captures lorsqu’un export, un PDF de commande ou un document bancaire est disponible."]),
                ("Contactez par des canaux contrôlés", ["Envoyez une notification écrite claire via la plateforme et l’adresse contractuelle, demandant un statut ou un remboursement avant une date précise.", "Évitez les menaces et les messages émotionnels répétés, qui rendent la chronologie moins lisible."]),
                ("Protégez les délais restants", ["Vérifiez immédiatement les délais de la marketplace, Trade Assurance, carte, virement, assurance et contrat.", "La demande du fournisseur d’attendre ne prolonge pas automatiquement le délai d’un tiers."]),
            ],
            "mistakes": ["Payer de nouveaux frais pour débloquer la marchandise ou le remboursement sans vérification", "Supprimer la conversation après quelques captures", "Accuser publiquement des personnes non concernées", "Attendre plusieurs semaines avant de vérifier les délais"],
            "faq": [("Le silence prouve-t-il une fraude ?", "Non. Il prouve l’absence de réponse, pas automatiquement l’intention. Décrivez précisément les faits et conservez paiement et promesses."), ("Quel est le document le plus important ?", "Souvent l’ensemble commande ou facture, preuve de paiement, identité du fournisseur et messages indiquant ce qui devait suivre le paiement."), ("Faut-il publier les coordonnées du fournisseur ?", "Les accusations publiques créent des risques juridiques et pratiques. Commencez par la conservation des preuves et les voies formelles.")],
        },
        "supplier-not-refunding": {
            "title": "Le fournisseur chinois refuse de rembourser : que faire",
            "description": "Liste pratique de preuves et d’escalade lorsqu’un fournisseur chinois ou vendeur Alibaba refuse de restituer un acompte ou paiement.",
            "intro": "Une promesse de remboursement n’est pas un remboursement reçu. Conservez la trace du paiement, le fondement de l’annulation ou du défaut et tous les délais encore ouverts.",
            "summary": "Gardez une demande précise : somme payée, raison du remboursement, promesse du vendeur, montant réellement reçu et délai qui reste disponible.",
            "sections": [
                ("Confirmez le fondement du remboursement", ["Identifiez la raison exacte : absence d’expédition, annulation acceptée par écrit, défaut, mauvaise spécification, manque ou autre violation documentée.", "Gardez les conditions de commande et le message où le fournisseur accepte l’annulation, reconnaît le problème ou promet le remboursement."]),
                ("Suivez l’argent", ["Conservez confirmation de paiement, bénéficiaire, transaction de plateforme, statut du remboursement et relevé bancaire montrant l’absence de crédit.", "En cas de remboursement partiel, indiquez le paiement initial, la somme reçue et le solde exact."]),
                ("Fixez un seul délai écrit", ["Envoyez une demande concise avec numéro de commande, montant, motif, liste des preuves, moyen de remboursement et date de réponse raisonnable.", "Ne remplacez pas une procédure ouverte par des promesses privées sans fin ; préservez les délais de plateforme, carte, banque ou assurance."]),
                ("Préparez la voie suivante", ["Selon le paiement et le contrat, les options peuvent inclure plateforme, litige de paiement, banque, assureur, mise en demeure, médiation, arbitrage ou tribunal.", "N’affirmez pas une fraude comme un fait sans preuve ; décrivez plutôt les comportements vérifiables."]),
            ],
            "mistakes": ["Fermer le litige avant réception des fonds", "Envoyer de l’argent supplémentaire pour débloquer le remboursement", "Indiquer des montants différents selon les messages", "Laisser expirer les délais de la plateforme ou du paiement"],
            "faq": [("Une capture de la promesse de remboursement suffit-elle ?", "Elle aide, mais joignez la commande, le paiement, le motif et un relevé bancaire ou de plateforme montrant que l’argent n’est pas arrivé."), ("Faut-il continuer à négocier en privé ?", "Seulement si cela ne met pas en danger un délai de plateforme, banque, carte ou contrat. Les échanges doivent rester courts et écrits."), ("ChinaTradeResolve garantit-il le remboursement ?", "Non. Le service aide à organiser faits et preuves, mais ne peut promettre un remboursement ni remplacer un avocat ou une autorité.")],
        },
        "wrong-material-size-color": {
            "title": "Mauvais matériau, dimensions ou couleur : comment le prouver",
            "description": "Comparer spécification approuvée, échantillon et marchandise lorsque matériau, dimensions, couleur ou modèle ne correspondent pas.",
            "intro": "Une réclamation de mauvaise spécification est plus solide si l’exigence finale peut être identifiée et si l’écart peut être mesuré ou vérifié indépendamment.",
            "summary": "Placez côte à côte la promesse et le résultat : spécification finale, date d’approbation, test ou mesure, quantité touchée et solution demandée.",
            "sections": [
                ("Identifiez la version finale approuvée", ["Gardez bon de commande final, plans, code couleur, description du matériau, validation d’échantillon et révisions ultérieures.", "Résolvez toute contradiction entre un ancien message et la spécification finale signée ou enregistrée sur la plateforme."]),
                ("Mesurez l’écart", ["Utilisez outils étalonnés, nuanciers, étiquettes, laboratoire ou expertise lorsque le problème n’est pas visible à l’œil nu.", "Consignez méthode, date, identité de l’échantillon et chaîne de garde pour tout test externe."]),
                ("Montrez l’importance commerciale", ["Expliquez l’effet sur l’usage, la conformité, la revente, la sécurité, la compatibilité ou la commande client convenue.", "N’affirmez pas qu’un écart est essentiel s’il n’a aucun effet documenté sur la transaction."]),
                ("Choisissez une solution proportionnée", ["Indiquez si l’écart justifie remplacement, reprise, réduction de prix, remboursement partiel, rejet ou annulation selon les règles applicables.", "Calculez le montant à partir de la quantité touchée et des coûts prouvés, pas d’une estimation arrondie."]),
            ],
            "mistakes": ["Utiliser la couleur d’un écran pour prouver un code couleur", "Qualifier un matériau de faux sans test ni document fiable", "Ignorer une modification approuvée ultérieurement", "Ne pas indiquer combien d’unités sont concernées"],
            "faq": [("Les photos suffisent-elles pour prouver le mauvais matériau ?", "Pas toujours. La composition exige souvent étiquettes, aveu du fournisseur, documents techniques ou test indépendant."), ("Que faire si l’échantillon et le bon de commande se contredisent ?", "Conservez les deux et identifiez le document accepté comme final. L’ordre des validations est essentiel."), ("Faut-il tester chaque unité ?", "Pas toujours, mais l’échantillon doit être représentatif et la méthode consignée.")],
        },
    },
}


INTERNATIONAL_GUIDES["de"] = {
    "alibaba-dispute-closed-no-refund": {
        "title": "Alibaba hat den Streitfall ohne Erstattung geschlossen: Was prüfen?",
        "description": "Strukturierte Checkliste zur Prüfung einer Alibaba-Entscheidung, fehlender Beweise, Fristen und möglicher weiterer Schritte.",
        "intro": "Die Schließung eines Plattformstreits erklärt nicht automatisch, ob Beweise fehlten, der Antrag widersprüchlich war, eine Frist versäumt wurde oder noch ein anderer Prüfungsweg offensteht.",
        "summary": "Sichern Sie die vollständige Fallakte, bestimmen Sie die genaue Entscheidung und Regel und vergleichen Sie die eingereichten Beweise mit dem Problem und der beantragten Lösung.",
        "sections": [
            ("Vollständige Streitakte sichern", ["Laden Sie Antrag, Verkäuferantwort, Plattformfragen, Beweisliste, Statusänderungen, Entscheidung und Schließungsdatum herunter oder speichern Sie Screenshots.", "Bewahren Sie die Bestellseite und die für die Transaktion geltende Fassung der Trade-Assurance- oder sonstigen Bedingungen auf."]),
            ("Genannten Grund lesen", ["Unterscheiden Sie verfahrensbedingte Schließung, Fristproblem, unzureichende Beweise und inhaltliche Ablehnung.", "Gehen Sie nicht davon aus, dass die Entscheidung einen Punkt behandelt hat, der nie klar vorgetragen oder belegt wurde."]),
            ("Eigene Einreichung prüfen", ["Kontrollieren Sie, ob Daten, Beträge, beantragte Abhilfe und Hauptproblem in allen Streitphasen konsistent blieben.", "Ordnen Sie jede wichtige Aussage einer konkreten Datei zu und notieren Sie von Alibaba angeforderte, aber nicht eingereichte oder besprochene Nachweise."]),
            ("Verbleibende Wege erfassen", ["Prüfen Sie Überprüfung, Beschwerde, Zahlungsdienstleister, Versicherer, formelle Aufforderung, Mediation, Schiedsverfahren oder Gericht.", "Fristen und Zuständigkeit hängen von Vertrag, Unternehmen, Zahlungsweg und Ort ab; verlassen Sie sich nicht auf eine allgemeine Internetfrist."]),
        ],
        "mistakes": ["Seiten des geschlossenen Falls löschen", "Eine neue unbelegte Geschichte vortragen", "Plattformentscheidung mit Gerichtsurteil gleichsetzen", "Externe Zahlungs- oder Vertragsfristen versäumen"],
        "faq": [("Kann ein geschlossener Alibaba-Streit wieder geöffnet werden?", "Das hängt vom Status, dem aktuellen Verfahren und neuen Beweisen ab. Sichern Sie die Akte und prüfen Sie die im Konto angezeigten Optionen."), ("Bedeutet die Schließung, dass der Lieferant Recht hatte?", "Nicht zwingend. Ein Fall kann aus Verfahrens- oder Beweisgründen geschlossen werden. Lesen Sie Wortlaut und Verlauf genau."), ("Was gehört in einen Prüfungsantrag?", "Eine knappe Chronologie, der konkret behauptete Fehler, die dafür sprechenden Beweise und ein eindeutig beantragtes Ergebnis.")],
    },
    "customs-clearance-problem": {
        "title": "Ware aus China hängt beim Zoll fest: Checkliste für den Lieferantenstreit",
        "description": "Beweise ordnen, wenn chinesische Ware wegen Rechnung, Tarifierung, Zertifikaten oder Kennzeichnung verzögert oder zurückgewiesen wird.",
        "intro": "Ein Zollproblem ist nicht automatisch eine Vertragsverletzung des Lieferanten. Klären Sie zunächst den offiziellen Grund, den Einführer, den Incoterm und wer welches Dokument oder welche Compliance-Pflicht zugesagt hat.",
        "summary": "Beginnen Sie mit der schriftlichen Zollmitteilung und ordnen Sie jeden fehlenden oder falschen Punkt Vertrag, Versandunterlagen und verantwortlicher Partei zu.",
        "sections": [
            ("Offiziellen Grund beschaffen", ["Fordern Sie die Mitteilung von Zoll, Broker, Frachtführer oder Behörde an, aus der fehlende, widersprüchliche, verbotene oder geprüfte Punkte hervorgehen.", "Unterscheiden Sie eine normale Dokumentenanforderung von Festhalten, Beschlagnahme, Zurückweisung, Rücksendung oder Vernichtungsrisiko."]),
            ("Verantwortlichkeiten zuordnen", ["Prüfen Sie Incoterm, Einführer, Brokeranweisungen und Vertragszusagen zu Tarifierung, Ursprung, Wert, Zertifikaten und Kennzeichnung.", "Nehmen Sie nicht an, dass „door to door“ ohne Prüfung der schriftlichen Vereinbarung alle gesetzlichen Pflichten überträgt."]),
            ("Dokumentenkette erhalten", ["Sichern Sie Handelsrechnung, Packliste, Konnossement oder Luftfrachtbrief, HS-Code, Ursprungsnachweise, Zertifikate, Erklärungen und Lieferantenanweisungen.", "Dokumentieren Sie jede Korrektur und den Aussteller, damit die Prüfspur erhalten bleibt."]),
            ("Kosten und Fristen kontrollieren", ["Verfolgen Sie Lagergeld, Standgeld, Broker-, Prüf-, Rücksende- und Vernichtungsfristen mit Rechnungen oder Mitteilungen.", "Prüfen Sie vor einer neuen Zahlung an den Lieferanten den Empfänger und verlangen Sie schriftlich, welches Problem die Zahlung löst."]),
        ],
        "mistakes": ["Nur der Zusammenfassung des Lieferanten vertrauen", "Rechnungen ändern, ohne das Original zu sichern", "Lager- oder Aufgabe-Fristen ignorieren", "Lieferantenverantwortung ohne Incoterm-Prüfung annehmen"],
        "faq": [("Wer haftet, wenn der Zoll die Ware stoppt?", "Das hängt vom offiziellen Grund, Einfuhrrecht, Einführer, Incoterm und den Vertragszusagen ab. Ausgangspunkt ist die Zollmitteilung."), ("Soll der Lieferant eine neue Rechnung ausstellen?", "Nur wenn ein echter Fehler berichtigt werden muss. Original sichern und keine falschen Werte oder Beschreibungen verwenden."), ("Können Zollkosten vom Lieferanten verlangt werden?", "Möglicherweise, wenn eine dokumentierte Pflichtverletzung sie verursacht hat und Vertrag oder Recht einen Ersatz zulassen.")],
    },
    "damaged-or-short-shipment": {
        "title": "Beschädigte oder fehlende Ware aus China: Anspruch dokumentieren",
        "description": "Beweischeckliste für beschädigte Kartons, gebrochene Ware, Fehlmengen, Unterlieferung oder unvollständige Lieferung.",
        "intro": "Schadens- und Fehlmengenfälle hängen stark von Beweisen bei der Annahme ab. Fotografieren Sie den ungeöffneten Zustand, Zählmethode, Etiketten und Frachtunterlagen vor Umpacken oder Weitergabe.",
        "summary": "Zeigen Sie vereinbarte und gelieferte Menge, Zustand bei Eingang, Prüfverfahren und finanzielle Auswirkung von Schaden oder Fehlmenge.",
        "sections": [
            ("Ankunftszustand dokumentieren", ["Fotografieren Sie Container, Palette oder Kartons vor dem Öffnen, einschließlich Siegel, Etiketten, Dellen, Feuchtigkeit und sichtbarer Schäden.", "Bewahren Sie Ablieferbelege auf und vermerken Sie Vorbehalte oder Schäden gegenüber dem Frachtführer."]),
            ("Systematisch zählen und prüfen", ["Nutzen Sie ein Zählblatt mit Kartonnummern, SKU, Charge und prüfender Person.", "Geben Sie bei Schäden an, wie viele Einheiten geprüft wurden, wie viele ausfielen und wie die Stichprobe ausgewählt wurde."]),
            ("Frachtführer- und Lieferantenfragen trennen", ["Vergleichen Sie Verpackungspflichten, Incoterms, Transportdokumente und den vertraglichen Gefahrübergang.", "Nicht jeder Transportschaden ist automatisch Sache des Lieferanten und nicht jeder Verpackungsfehler Sache des Frachtführers."]),
            ("Begründete Abhilfe berechnen", ["Ordnen Sie jede fehlende oder beschädigte Einheit dem Rechnungspreis und belegten Prüf-, Entsorgungs- oder Reparaturkosten zu.", "Bewahren Sie Ware und Verpackung auf, bis geklärt ist, ob eine Besichtigung erforderlich ist."]),
        ],
        "mistakes": ["Reinen Ablieferbeleg trotz sichtbarer Schäden unterschreiben", "Verpackung vor Prüfung entsorgen", "Gesamtbestellung nach Prüfung nur einer Einheit beanstanden", "Pauschale Erstattung ohne Berechnung verlangen"],
        "faq": [("Muss jeder Karton geöffnet werden?", "Verwenden Sie einen nachvollziehbaren Prüfplan und dokumentieren Sie den Umfang. Er hängt von Sendung und Streitweg ab."), ("Wer haftet für Transportschäden?", "Entscheidend sind Vertrag, Incoterms, Frachtunterlagen, Verpackungspflichten und tatsächliche Ursache."), ("Hilft ein Lagerbericht?", "Ja, besonders mit Eingangszeit, Siegelzustand, Kartonzahl, Fotos und Prüfverfahren.")],
    },
    "order-not-delivered-tracking-problem": {
        "title": "Bestellung aus China nicht zugestellt: Tracking- und Beweischeckliste",
        "description": "Was sammeln, wenn Tracking ungültig oder eingefroren ist, an den falschen Ort führt oder eine nicht erhaltene Zustellung zeigt.",
        "intro": "Nichtzustellung nach Versand ist etwas anderes als Nichtversand. Erstellen Sie eine Frachtführer-Chronologie und bestimmen Sie Route, Empfänger, Zustellscan und Ausnahmen.",
        "summary": "Sichern Sie vereinbarten Zielort, Frachtführerangaben, Trackingverlauf, Zustellnachweis, Kommunikation und den Punkt, an dem die Sendung stoppte oder fehlgeleitet wurde.",
        "sections": [
            ("Trackingverlauf sichern", ["Speichern Sie Frachtführername, vollständige Nummer und alle datierten Scans statt nur des letzten Status.", "Prüfen Sie die Nummer im offiziellen System und dokumentieren Sie Abweichungen bei Ziel, Gewicht oder Service."]),
            ("Zustellnachweis anfordern", ["Fordern Sie Zustelladresse, Empfängername, Unterschrift, Foto, GPS oder lokalen Frachtführereintrag an, soweit verfügbar.", "Ein allgemeiner Status „zugestellt“ beweist nicht, dass der richtige Empfänger die Ware erhalten hat."]),
            ("Übergaben nachvollziehen", ["Ermitteln Sie Spediteure, Konsolidierer, Zollbroker und letzte Meile einschließlich aller Ersatz-Trackingnummern.", "Dokumentieren Sie den Übergang von Gefahr und Verantwortung nach Vertrag und Incoterm."]),
            ("Richtige Stellen benachrichtigen", ["Informieren Sie Verkäufer, Plattform, Frachtführer, Versicherer und Zahlungsdienstleister rechtzeitig schriftlich.", "Bewahren Sie Vorgangsnummern sowie Verpackung und Dokumente bei Teillieferungen auf."]),
        ],
        "mistakes": ["Tracking-Screenshot ohne Frachtführername verwenden", "Reklamationsfrist des Frachtführers verstreichen lassen", "Lagerzustellung mit Zustellung an Käufer verwechseln", "Ersatz-Trackingnummern nicht dokumentieren"],
        "faq": [("Tracking sagt zugestellt, aber nichts ist da. Was tun?", "Fordern Sie einen detaillierten Zustellnachweis an und vergleichen Sie Adresse, Empfänger, Gewicht und lokalen Eintrag mit der Bestellung."), ("Haftet der Verkäufer immer für Verlust im Transit?", "Nein. Vertrag, Incoterms, Versicherung und Verlustort sind entscheidend."), ("Was bei einer falschen Trackingnummer?", "Sichern Sie die offizielle Antwort des Frachtführers, Widersprüche und Lieferantenkommunikation und bleiben Sie bei belegbaren Tatsachen.")],
    },
    "supplier-certificate-problem": {
        "title": "Falsches oder ungültiges Zertifikat aus China: Was prüfen?",
        "description": "Beweischeckliste bei fehlendem, unpassendem, nicht prüfbarem, abgelaufenem oder für den Zielmarkt ungeeignetem Zertifikat.",
        "intro": "Ein Logo oder PDF mit der Bezeichnung „Zertifikat“ genügt nicht. Entscheidend ist, welches Dokument zugesagt wurde, wer es ausgestellt hat, welches Produkt und welche Norm es abdeckt und ob es für den Zielmarkt gilt.",
        "summary": "Vergleichen Sie das zugesagte Compliance-Dokument mit Aussteller, Nummer, Produktmodell, Norm, Geltungsbereich, Daten und Zielmarktanforderungen.",
        "sections": [
            ("Zusage sichern", ["Bewahren Sie Nachrichten, Angebot und Bestellklausel auf, die Zertifikat, Prüfbericht, Erklärung oder Registrierung benennen.", "Notieren Sie, ob das Dokument Voraussetzung für Zahlung, Produktionsfreigabe, Versand oder Einfuhr war."]),
            ("Dokument verifizieren", ["Prüfen Sie Ausstellerkontakt, Nummer, Modell, Antragsteller, Hersteller, Norm, Ausgabe- und Ablaufdatum sowie öffentliche Datenbanken.", "Kontaktieren Sie den angegebenen Aussteller bei Bedarf über unabhängig ermittelte Kontaktdaten."]),
            ("Dokumentarten unterscheiden", ["Prüfbericht, Zertifikat, Konformitätserklärung, Werksaudit und Produktregistrierung sind nicht austauschbar.", "Bezeichnen Sie ein Dokument nicht ohne belastbare Beweise als gefälscht; nennen Sie die konkrete Abweichung oder fehlgeschlagene Prüfung."]),
            ("Bezug zur Transaktion herstellen", ["Erklären Sie, warum das fehlende oder ungeeignete Dokument rechtmäßige Einfuhr, Verkauf, Installation oder vereinbarte Nutzung verhindert.", "Sichern Sie Schreiben von Zoll, Labor, Berater oder Behörde, die das Problem benennen."]),
        ],
        "mistakes": ["Zertifikat für anderes Modell oder Hersteller akzeptieren", "Nur einem Verkäuferlink vertrauen", "Prüfbericht mit Marktzulassung verwechseln", "Fälschung vor Verifizierung behaupten"],
        "faq": [("Wie lässt sich ein Zertifikat prüfen?", "Prüfen Sie Aussteller, Nummer, Geltungsbereich, Modell und Daten unabhängig. Anforderungen unterscheiden sich nach Produkt und Markt."), ("Beweist ein CE-Zeichen die Konformität?", "Nein. Ein Zeichen allein belegt nicht, dass alle einschlägigen Pflichten und Unterlagen erfüllt sind."), ("Kann das Rücktritt oder Erstattung stützen?", "Möglicherweise, wenn das Dokument vereinbarte Bedingung war oder die Ware nicht rechtmäßig wie vorgesehen genutzt werden kann.")],
    },
    "supplier-disappeared-after-payment": {
        "title": "Chinesischer Lieferant nach Zahlung verschwunden: Erste Schritte",
        "description": "Was sichern und prüfen, wenn ein chinesischer Lieferant nach Anzahlung oder Vollzahlung nicht mehr antwortet.",
        "intro": "Schweigen nach Zahlung kann verschiedene Gründe haben. Die unmittelbare Aufgabe bleibt: Transaktion, Identität und Kommunikation sichern, bevor Konten oder Seiten geändert werden.",
        "summary": "Dokumentieren Sie, wer das Geld erhielt, was zugesagt wurde, das letzte bestätigte Produktions- oder Versandereignis und jeden erfolglosen Kontaktversuch.",
        "sections": [
            ("Identität und Transaktion sichern", ["Speichern Sie Firmenname, Registerdaten, Alibaba- oder Marktplatzprofil, Website, Adressen, Bankempfänger und Rechnung.", "Exportieren Sie möglichst den vollständigen Chat mit Daten, Namen, Anhängen und Kontext von Sprachnachrichten."]),
            ("Kontoveränderungen prüfen", ["Dokumentieren Sie gelöschte Angebote, Namensänderungen, gesperrte Konten, unzustellbare E-Mails und abgeschaltete Nummern.", "Verlassen Sie sich nicht nur auf Screenshots, wenn Chat-Export, Bestell-PDF oder Bankbeleg verfügbar ist."]),
            ("Kontrollierte Kontaktwege nutzen", ["Senden Sie eine klare schriftliche Mitteilung über Plattform und Vertragsadresse mit Frist für Status oder Erstattung.", "Vermeiden Sie Drohungen und wiederholte emotionale Nachrichten; sie erschweren die Chronologie."]),
            ("Verbleibende Fristen schützen", ["Prüfen Sie sofort Marktplatz-, Trade-Assurance-, Karten-, Banküberweisungs-, Versicherungs- und Vertragsfristen.", "Die Bitte des Lieferanten zu warten verlängert nicht automatisch die Frist eines Dritten."]),
        ],
        "mistakes": ["Neue Gebühr für Ware oder Erstattung ungeprüft zahlen", "Chat nach wenigen Screenshots löschen", "Unbeteiligte öffentlich beschuldigen", "Wochenlang Streitfristen nicht prüfen"],
        "faq": [("Beweist Schweigen Betrug?", "Nein. Es belegt Nichtantwort, nicht automatisch Absicht. Beschreiben Sie die Tatsachen genau und sichern Sie Zahlung und Zusagen."), ("Welches Dokument ist am wichtigsten?", "Meist die Kombination aus Bestellung oder Rechnung, Zahlungsbeleg, Lieferantenidentität und Nachrichten über die Leistung nach Zahlung."), ("Sollten Lieferantendaten veröffentlicht werden?", "Öffentliche Anschuldigungen bergen rechtliche und praktische Risiken. Beginnen Sie mit Beweissicherung und formellen Kanälen.")],
    },
    "supplier-not-refunding": {
        "title": "Chinesischer Lieferant verweigert die Erstattung: Nächste Schritte",
        "description": "Praktische Beweis- und Eskalationscheckliste, wenn ein chinesischer Lieferant oder Alibaba-Verkäufer Anzahlung oder Zahlung nicht zurückzahlt.",
        "intro": "Eine Erstattungszusage ist keine eingegangene Erstattung. Sichern Sie Zahlungsweg, vereinbarten Storno- oder Mangelgrund und alle Fristen.",
        "summary": "Halten Sie die Forderung eng: gezahlter Betrag, Erstattungsgrund, Verkäuferzusage, tatsächlich erhaltene Summe und noch offene Frist.",
        "sections": [
            ("Erstattungsgrund bestätigen", ["Benennen Sie den genauen Grund: Nichtversand, schriftlich akzeptierte Stornierung, Mängel, falsche Spezifikation, Fehlmenge oder andere belegte Pflichtverletzung.", "Sichern Sie Bestellbedingungen und die Nachricht, in der der Lieferant Storno akzeptiert, Problem anerkennt oder Erstattung zusagt."]),
            ("Geldfluss verfolgen", ["Bewahren Sie Zahlungsbestätigung, Empfängerdaten, Plattformtransaktion, Erstattungsstatus und Kontoauszug ohne Gutschrift auf.", "Bei Teilerstattung nennen Sie Ausgangszahlung, bereits erhaltenen Betrag und genauen offenen Saldo."]),
            ("Eine schriftliche Frist setzen", ["Senden Sie eine knappe Aufforderung mit Bestellnummer, Betrag, Grund, Beweisliste, Zahlungsweg und angemessener Antwortfrist.", "Ersetzen Sie ein Plattformverfahren nicht durch endlose private Zusagen und schützen Sie Karten-, Bank-, Versicherungs- und Plattformfristen."]),
            ("Nächsten Weg vorbereiten", ["Je nach Zahlung und Vertrag kommen Plattformverfahren, Zahlungsstreit, Bankanfrage, Versicherer, formelle Aufforderung, Mediation, Schiedsverfahren oder Gericht in Betracht.", "Behaupten Sie Betrug nicht als Tatsache ohne Beleg; beschreiben Sie das überprüfbare Verhalten."]),
        ],
        "mistakes": ["Streit schließen, bevor Geld eingeht", "Zusätzliches Geld zur Freigabe der Erstattung senden", "Unterschiedliche Forderungsbeträge verwenden", "Zahlungs- oder Plattformfristen verstreichen lassen"],
        "faq": [("Reicht ein Screenshot der Erstattungszusage?", "Er hilft, sollte aber mit Bestellung, Zahlungsnachweis, Erstattungsgrund und Konto- oder Plattformbeleg ohne Eingang kombiniert werden."), ("Soll privat weiterverhandelt werden?", "Nur solange keine Plattform-, Bank-, Karten- oder Vertragsfrist gefährdet wird. Kurz und schriftlich verhandeln."), ("Garantiert ChinaTradeResolve die Rückzahlung?", "Nein. Der Dienst hilft bei der Strukturierung von Tatsachen und Beweisen, verspricht aber keine Erstattung und ersetzt keinen Anwalt oder Behörde.")],
    },
    "wrong-material-size-color": {
        "title": "Falsches Material, Maß oder Farbe geliefert: So beweisen Sie es",
        "description": "Genehmigte Spezifikation, Muster und Ware vergleichen, wenn Material, Abmessungen, Farbe oder Modell abweichen.",
        "intro": "Ein Anspruch wegen falscher Spezifikation ist am stärksten, wenn die endgültig genehmigte Anforderung feststeht und die Abweichung messbar oder unabhängig prüfbar ist.",
        "summary": "Stellen Sie Zusage und Ergebnis gegenüber: Endfassung, Genehmigungsdatum, Test oder Messung, betroffene Menge und verlangte Abhilfe.",
        "sections": [
            ("Endgültige genehmigte Fassung bestimmen", ["Sichern Sie endgültige Bestellung, Zeichnungen, Farbcode, Materialbeschreibung, Musterfreigabe und spätere Änderungen.", "Klären Sie Widersprüche zwischen frühem Chat und endgültiger unterschriebener oder auf der Plattform gespeicherter Spezifikation."]),
            ("Abweichung messen", ["Nutzen Sie kalibrierte Werkzeuge, Farbreferenzen, Etiketten, Labor- oder Sachverständigenprüfung, wenn die Abweichung nicht visuell feststellbar ist.", "Dokumentieren Sie Methode, Datum, Probenidentität und Beweiskette externer Tests."]),
            ("Geschäftliche Relevanz zeigen", ["Erklären Sie Auswirkungen auf Nutzung, Compliance, Wiederverkauf, Sicherheit, Kompatibilität oder den vereinbarten Kundenauftrag.", "Bezeichnen Sie eine Abweichung nicht als wesentlich, wenn keine belegte Auswirkung auf das Geschäft besteht."]),
            ("Verhältnismäßige Abhilfe wählen", ["Nennen Sie Ersatz, Nacharbeit, Preisnachlass, Teilerstattung, Zurückweisung oder Storno nach den anwendbaren Bedingungen.", "Berechnen Sie den Betrag aus betroffener Menge und belegten Kosten statt als runde Schätzung."]),
        ],
        "mistakes": ["Bildschirmfarbe als Beweis für Farbcode nutzen", "Material ohne Prüfung als gefälscht bezeichnen", "Später genehmigte Änderung ignorieren", "Betroffene Stückzahl nicht angeben"],
        "faq": [("Reichen Fotos für falsches Material?", "Nicht immer. Zusammensetzung erfordert oft Etiketten, Lieferanteneingeständnis, technische Unterlagen oder unabhängige Prüfung."), ("Was bei Widerspruch zwischen Muster und Bestellung?", "Beides sichern und bestimmen, welches Dokument endgültig akzeptiert wurde. Die Reihenfolge der Freigaben ist wichtig."), ("Muss jede Einheit geprüft werden?", "Nicht immer, aber die Stichprobe muss repräsentativ und die Methode dokumentiert sein.")],
    },
}

INTERNATIONAL_GUIDES["es"] = {
    "alibaba-dispute-closed-no-refund": {
        "title": "Alibaba cerró la disputa sin reembolso: qué revisar",
        "description": "Lista estructurada para revisar una decisión de Alibaba, pruebas omitidas, plazos y posibles vías de escalación.",
        "intro": "El cierre de una disputa no explica por sí solo si faltaron pruebas, si la reclamación fue incoherente, si venció un plazo o si todavía existe otra vía de revisión.",
        "summary": "Conserve el expediente completo, identifique la decisión y la regla citada, y compare las pruebas presentadas con el problema y la solución solicitada.",
        "sections": [
            ("Guarde todo el expediente", ["Descargue la reclamación, respuesta del vendedor, preguntas de la plataforma, lista de pruebas, cambios de estado, decisión y fecha de cierre.", "Conserve la página del pedido y la versión de Trade Assurance u otras condiciones aplicables a la operación."]),
            ("Lea el motivo indicado", ["Diferencie un cierre procesal, un problema de plazo, una conclusión por pruebas insuficientes y un rechazo de fondo.", "No dé por hecho que la decisión trató un punto que nunca se explicó ni documentó con claridad."]),
            ("Revise su propia presentación", ["Compruebe que fechas, importes, solución solicitada y problema principal fueron coherentes en todas las rondas.", "Vincule cada afirmación importante con un archivo concreto y anote las pruebas que Alibaba pidió pero no recibió o no comentó."]),
            ("Trace las opciones restantes", ["Revise si siguen disponibles reconsideración, apelación, queja, disputa de pago, seguro, requerimiento formal, mediación, arbitraje o tribunales.", "Los plazos y la jurisdicción dependen del contrato, entidad, forma de pago y lugar; no use un plazo genérico encontrado en internet."]),
        ],
        "mistakes": ["Borrar las páginas del caso cerrado", "Iniciar una nueva reclamación con una historia distinta y sin pruebas", "Confundir la decisión de una plataforma con una sentencia", "Perder plazos bancarios o contractuales mientras espera soporte"],
        "faq": [("¿Puede reabrirse una disputa cerrada de Alibaba?", "Depende del estado del caso, del procedimiento vigente y de nuevas pruebas disponibles. Conserve el expediente y revise las opciones de la cuenta."), ("¿El cierre demuestra que el proveedor tenía razón?", "No necesariamente. El caso puede cerrarse por razones procesales o probatorias. Lea el texto exacto y el historial."), ("¿Qué debe contener una solicitud de revisión?", "Una cronología breve, el error concreto alegado, las pruebas que lo sustentan y un resultado específico solicitado.")],
    },
    "customs-clearance-problem": {
        "title": "Mercancía china retenida en aduanas: lista para la disputa",
        "description": "Cómo organizar pruebas cuando aduanas retrasa o rechaza mercancías por facturas, clasificación, certificados o marcado.",
        "intro": "Un problema aduanero no es automáticamente un incumplimiento del proveedor. Primero identifique el motivo oficial, el importador registrado, el Incoterm y quién prometió cada documento o paso de cumplimiento.",
        "summary": "Empiece por la notificación escrita de aduanas y relacione cada elemento faltante o incorrecto con el contrato, documentos de envío y parte responsable.",
        "sections": [
            ("Obtenga el motivo oficial", ["Solicite la notificación de aduanas, agente, transportista o autoridad que indique qué falta, es incoherente, está prohibido o se revisa.", "Distinga una solicitud normal de documentos de una retención, incautación, rechazo, devolución o riesgo de destrucción."]),
            ("Asigne responsabilidades", ["Revise el Incoterm, importador, instrucciones al agente y promesas contractuales sobre clasificación, origen, valor, certificados y marcado.", "No suponga que «puerta a puerta» transfiere todas las obligaciones legales sin leer el acuerdo escrito."]),
            ("Conserve la cadena documental", ["Guarde factura comercial, packing list, conocimiento de embarque o guía aérea, código HS, documentos de origen, certificados, declaraciones e instrucciones del proveedor.", "Registre cada documento corregido y quién lo emitió para mantener la trazabilidad."]),
            ("Controle costes y plazos", ["Lleve control de almacenaje, demoras, agente, ensayos, devolución y destrucción con facturas o avisos.", "Antes de pagar una nueva tasa solicitada por el proveedor, verifique al destinatario y pida una explicación escrita de qué resuelve."]),
        ],
        "mistakes": ["Confiar solo en el resumen del proveedor", "Modificar facturas sin guardar el original", "Ignorar plazos de almacenaje o abandono", "Culpar al proveedor sin revisar Incoterm y función del importador"],
        "faq": [("¿Quién responde cuando aduanas detiene la mercancía?", "Depende del motivo oficial, la normativa de importación, el importador, el Incoterm y las promesas contractuales."), ("¿Debe el proveedor emitir una factura nueva?", "Solo para corregir un error real. Conserve la original y no utilice valores o descripciones falsos."), ("¿Pueden reclamarse al proveedor los costes aduaneros?", "Posiblemente, si un incumplimiento documentado los causó y el contrato o la ley permiten recuperarlos.")],
    },
    "damaged-or-short-shipment": {
        "title": "Mercancía china dañada o incompleta: cómo documentar la reclamación",
        "description": "Pruebas para cajas dañadas, productos rotos, unidades faltantes, envío corto o entrega incompleta de un proveedor chino.",
        "intro": "Los casos de daño y faltantes dependen mucho de las pruebas creadas al recibir. Fotografíe el estado cerrado, método de recuento, etiquetas y documentos del transportista antes de reembalar o distribuir.",
        "summary": "Muestre la cantidad acordada, la recibida, el estado a la llegada, el método de inspección y el efecto económico del daño o faltante.",
        "sections": [
            ("Documente el estado de llegada", ["Fotografíe contenedor, palé o cajas antes de abrir, incluidos precintos, etiquetas, golpes, humedad y daños visibles.", "Conserve los comprobantes de entrega y anote reservas o daños ante el transportista."]),
            ("Cuente y muestree de forma sistemática", ["Use una hoja de recuento con números de caja, SKU, lote y persona que hizo la revisión.", "Para daños, indique cuántas unidades se inspeccionaron, cuántas fallaron y cómo se eligió la muestra."]),
            ("Separe problemas del transportista y proveedor", ["Compare obligaciones de embalaje, Incoterms, documentos de transporte y momento de transmisión del riesgo.", "No suponga que toda pérdida en tránsito es del proveedor ni que todo defecto de embalaje es del transportista."]),
            ("Calcule una solución respaldada", ["Relacione cada unidad faltante o dañada con su precio de factura y costes documentados de inspección, reparación o eliminación.", "Conserve mercancía y embalaje hasta que se confirme si hace falta una inspección."]),
        ],
        "mistakes": ["Firmar una entrega sin reservas pese a daños visibles", "Desechar el embalaje antes de inspeccionar", "Afirmar que todo el pedido está defectuoso tras revisar una unidad", "Pedir una suma global sin cálculo"],
        "faq": [("¿Debo abrir todas las cajas?", "Use un plan de inspección defendible y registre qué revisó. El alcance depende del envío y de la vía de reclamación."), ("¿Quién responde por daños en tránsito?", "Depende del contrato, Incoterms, documentos del transportista, obligaciones de embalaje y causa real."), ("¿Sirve un informe de almacén?", "Sí, especialmente si registra hora de recepción, precintos, número de cajas, fotografías y método de inspección.")],
    },
    "order-not-delivered-tracking-problem": {
        "title": "Pedido de China no entregado: seguimiento y pruebas",
        "description": "Qué reunir cuando el tracking es inválido, no avanza, fue entregado en otro lugar o muestra una entrega que no recibió.",
        "intro": "La falta de entrega después del envío es distinta de la falta de envío. Cree una cronología de transportistas e identifique ruta, destinatario, escaneo de entrega y excepciones.",
        "summary": "Conserve el destino acordado, datos del transportista, historial de seguimiento, prueba de entrega, comunicaciones y punto donde el envío se detuvo o desvió.",
        "sections": [
            ("Capture todo el historial de seguimiento", ["Guarde nombre del transportista, número completo y todos los escaneos fechados, no solo el último estado.", "Verifique el número en el sistema oficial y registre diferencias de destino, peso o servicio."]),
            ("Solicite prueba de entrega", ["Pida dirección de entrega, nombre del receptor, firma, fotografía, GPS o registro del transportista local cuando exista.", "Un estado genérico «entregado» no demuestra que el destinatario correcto recibió la mercancía."]),
            ("Rastree cada transferencia", ["Identifique transitarios, consolidadores, agentes aduaneros y última milla, incluidos todos los números sustitutos.", "Registre cuándo pasaron riesgo y responsabilidad según contrato e Incoterm."]),
            ("Notifique a las partes correctas", ["Avise por escrito y a tiempo al vendedor, plataforma, transportista, aseguradora y proveedor de pago cuando corresponda.", "Guarde referencias de reclamación y no tire embalajes o documentos de entregas parciales."]),
        ],
        "mistakes": ["Usar una captura sin nombre del transportista", "Dejar vencer el plazo de reclamación al transportista", "Confundir entrega a un almacén con entrega al comprador", "No guardar números de seguimiento sustitutos"],
        "faq": [("El tracking dice entregado pero no llegó, ¿qué hago?", "Solicite prueba detallada y compare dirección, receptor, peso y registro local con el pedido."), ("¿El vendedor siempre responde por una pérdida en tránsito?", "No. Importan contrato, Incoterms, seguro y lugar de la pérdida."), ("¿Qué hacer si el tracking es falso?", "Documente la respuesta oficial del transportista, incoherencias y mensajes del proveedor, sin concluir más de lo que prueban los datos.")],
    },
    "supplier-certificate-problem": {
        "title": "Certificado chino incorrecto o inválido: qué comprobar",
        "description": "Pruebas cuando falta un certificado, corresponde a otro producto, no puede verificarse, está vencido o no sirve para el mercado de destino.",
        "intro": "Un logotipo o PDF llamado «certificado» no basta. Hay que saber qué documento se prometió, quién lo emitió, qué producto y norma cubre y si vale en el mercado previsto.",
        "summary": "Compare el documento prometido con emisor, número, modelo, norma, alcance, fechas y requisitos del país de destino.",
        "sections": [
            ("Conserve lo prometido", ["Guarde mensajes, oferta y condición del pedido que indiquen certificado, informe de ensayo, declaración o registro que debía aportar el proveedor.", "Anote si era condición de pago, aprobación de producción, envío o importación."]),
            ("Verifique el documento", ["Compruebe contacto del emisor, número, modelo, solicitante, fabricante, norma, fechas y base pública disponible.", "Cuando sea importante, contacte al emisor mediante datos obtenidos de forma independiente."]),
            ("Distinga los tipos de documento", ["Informe de ensayo, certificado, declaración de conformidad, auditoría de fábrica y registro de producto no son equivalentes.", "No llame falso a un documento sin pruebas fiables; describa la incoherencia o verificación fallida."]),
            ("Conéctelo con la operación", ["Explique por qué el documento faltante o inadecuado impide importar, vender, instalar o usar legalmente el producto.", "Conserve comunicaciones de aduanas, laboratorio, consultor o autoridad que identifiquen el problema."]),
        ],
        "mistakes": ["Aceptar certificado de otro modelo o fabricante", "Confiar solo en un enlace del proveedor", "Confundir informe de ensayo con autorización de mercado", "Acusar de falsificación antes de verificar"],
        "faq": [("¿Cómo verifico un certificado?", "Compruebe de forma independiente el emisor, número, alcance, modelo y fechas. Los requisitos varían por producto y destino."), ("¿El logotipo CE prueba el cumplimiento?", "No. El marcado por sí solo no demuestra que se cumplan todas las obligaciones y documentos aplicables."), ("¿Puede justificar cancelación o reembolso?", "Posiblemente, si el documento era una condición acordada o el producto no puede utilizarse legalmente como se pretendía.")],
    },
    "supplier-disappeared-after-payment": {
        "title": "Proveedor chino desapareció tras el pago: primeras medidas",
        "description": "Qué conservar y comprobar si un proveedor chino deja de responder después de un depósito o pago completo.",
        "intro": "El silencio tras el pago puede tener varias explicaciones, pero la tarea inmediata es la misma: preservar pruebas de transacción, identidad y comunicaciones antes de que cambien cuentas o páginas.",
        "summary": "Registre quién recibió el dinero, qué se prometió, el último evento confirmado de producción o envío y todos los intentos de contacto sin respuesta.",
        "sections": [
            ("Conserve identidad y transacción", ["Guarde nombre de empresa, registro, perfil de Alibaba o marketplace, web, direcciones, beneficiario bancario y factura.", "Exporte el chat completo cuando sea posible, con fechas, nombres, adjuntos y contexto de notas de voz."]),
            ("Compruebe cambios en la cuenta", ["Documente anuncios eliminados, cambios de nombre, cuentas bloqueadas, correos devueltos y teléfonos desconectados.", "No dependa solo de capturas cuando exista exportación, PDF del pedido o documento bancario."]),
            ("Contacte por canales controlados", ["Envíe un aviso escrito claro por la plataforma y dirección contractual, pidiendo estado o reembolso antes de una fecha concreta.", "Evite amenazas y mensajes emocionales repetidos; dificultan revisar la cronología."]),
            ("Proteja los plazos restantes", ["Revise inmediatamente plazos de marketplace, Trade Assurance, tarjeta, transferencia, seguro y contrato.", "La petición del proveedor de esperar no amplía automáticamente el plazo de un tercero."]),
        ],
        "mistakes": ["Pagar una nueva tasa para liberar mercancía o reembolso sin verificar", "Borrar el chat tras unas capturas", "Acusar públicamente a personas no relacionadas", "Esperar semanas para revisar los plazos"],
        "faq": [("¿El silencio demuestra fraude?", "No. Demuestra falta de respuesta, no intención. Describa con precisión los hechos y conserve pago y promesas."), ("¿Cuál es el documento más importante?", "Normalmente la combinación de pedido o factura, prueba de pago, identidad del proveedor y mensajes sobre lo que debía ocurrir después."), ("¿Debo publicar los datos del proveedor?", "Las acusaciones públicas pueden crear riesgos legales y prácticos. Empiece por preservar pruebas y usar canales formales.")],
    },
    "supplier-not-refunding": {
        "title": "El proveedor chino se niega a reembolsar: qué hacer",
        "description": "Lista práctica de pruebas y escalación cuando un proveedor chino o vendedor de Alibaba no devuelve un depósito o pago.",
        "intro": "Una promesa de reembolso no equivale a un reembolso recibido. Conserve el rastro del pago, la base de cancelación o defecto y todos los plazos.",
        "summary": "Mantenga una reclamación concreta: qué se pagó, por qué procede el reembolso, qué prometió el vendedor, qué se recibió y qué plazo sigue abierto.",
        "sections": [
            ("Confirme la base del reembolso", ["Identifique el motivo exacto: falta de envío, cancelación aceptada por escrito, producto defectuoso, especificación incorrecta, faltante u otro incumplimiento documentado.", "Guarde condiciones del pedido y el mensaje donde el proveedor acepta cancelar, reconoce el problema o promete reembolsar."]),
            ("Siga el dinero", ["Conserve confirmación de pago, beneficiario, registro de plataforma, estado del reembolso y extracto bancario sin abono.", "En un reembolso parcial, indique pago original, importe recibido y saldo exacto pendiente."]),
            ("Use un solo plazo escrito", ["Envíe una demanda breve con número de pedido, importe, motivo, lista de pruebas, método de devolución y fecha razonable de respuesta.", "No sustituya un procedimiento abierto por promesas privadas interminables; proteja plazos de plataforma, tarjeta, banco o seguro."]),
            ("Prepare la siguiente vía", ["Según pago y contrato, puede haber proceso de plataforma, disputa de pago, banco, aseguradora, requerimiento, mediación, arbitraje o tribunal.", "No afirme fraude como hecho sin pruebas; describa la conducta verificable."]),
        ],
        "mistakes": ["Cerrar la disputa antes de recibir el dinero", "Enviar dinero extra para desbloquear el reembolso", "Usar distintos importes en diferentes mensajes", "Dejar vencer plazos de plataforma o pago"],
        "faq": [("¿Basta una captura de la promesa de reembolso?", "Ayuda, pero combínela con pedido, pago, motivo y registro bancario o de plataforma que muestre que no llegó."), ("¿Debo seguir negociando en privado?", "Solo mientras no ponga en riesgo un plazo de plataforma, banco, tarjeta o contrato. Mantenga la negociación breve y escrita."), ("¿ChinaTradeResolve garantiza recuperar el dinero?", "No. Ayuda a ordenar hechos y pruebas, pero no promete un reembolso ni sustituye a un abogado o autoridad.")],
    },
    "wrong-material-size-color": {
        "title": "Material, tamaño o color incorrectos: cómo demostrarlo",
        "description": "Cómo comparar especificación aprobada, muestra y mercancía cuando material, medidas, color o modelo no coinciden.",
        "intro": "Una reclamación por especificación incorrecta es más sólida cuando puede identificarse el requisito final y la diferencia puede medirse o verificarse de forma independiente.",
        "summary": "Ponga lado a lado promesa y resultado: especificación final, fecha de aprobación, ensayo o medición, cantidad afectada y solución solicitada.",
        "sections": [
            ("Identifique la versión final aprobada", ["Guarde pedido final, planos, código de color, descripción del material, aprobación de muestra y revisiones posteriores.", "Resuelva contradicciones entre un mensaje inicial y la especificación final firmada o guardada en la plataforma."]),
            ("Mida la diferencia", ["Use herramientas calibradas, referencias de color, etiquetas, laboratorio o peritaje cuando no pueda establecerse visualmente.", "Registre método, fecha, identidad de la muestra y cadena de custodia de cualquier prueba externa."]),
            ("Muestre la importancia comercial", ["Explique cómo afecta uso, cumplimiento, reventa, seguridad, compatibilidad o pedido del cliente.", "No afirme que una diferencia es material si no tiene efecto documentado sobre la operación."]),
            ("Elija una solución proporcional", ["Indique si corresponde sustitución, retrabajo, descuento, reembolso parcial, rechazo o cancelación según las condiciones.", "Calcule el importe por cantidad afectada y costes respaldados, no mediante una cifra redonda."]),
        ],
        "mistakes": ["Usar el color de una pantalla para probar un código", "Llamar falso a un material sin prueba fiable", "Ignorar una revisión posterior aprobada", "No identificar cuántas unidades están afectadas"],
        "faq": [("¿Bastan fotografías para probar el material incorrecto?", "A veces no. La composición puede requerir etiquetas, admisión del proveedor, documentos técnicos o ensayo independiente."), ("¿Qué pasa si la muestra y el pedido se contradicen?", "Conserve ambos e identifique cuál fue aceptado como final. La secuencia de aprobaciones importa."), ("¿Hay que probar cada unidad?", "No siempre, pero la muestra debe ser representativa y el método debe quedar registrado.")],
    },
}

INTERNATIONAL_GUIDES["sr"] = {
    "alibaba-dispute-closed-no-refund": {
        "title": "Alibaba je zatvorila spor bez povraćaja novca: šta proveriti",
        "description": "Strukturisana kontrolna lista za proveru odluke Alibabe, propuštenih dokaza, rokova i mogućih narednih koraka.",
        "intro": "Samo zatvaranje spora ne objašnjava da li su dokazi bili nedovoljni, zahtev nedosledan, rok propušten ili je ostao drugi put za preispitivanje.",
        "summary": "Sačuvajte ceo predmet, utvrdite tačnu odluku i navedeno pravilo, pa uporedite predate dokaze sa problemom i rešenjem koje ste tražili.",
        "sections": [
            ("Sačuvajte kompletan zapis spora", ["Preuzmite zahtev, odgovor prodavca, pitanja platforme, spisak dokaza, promene statusa, odluku i datum zatvaranja.", "Sačuvajte stranicu porudžbine i verziju Trade Assurance ili drugih uslova koji su važili za transakciju."]),
            ("Pročitajte navedeni razlog", ["Razdvojite proceduralno zatvaranje, problem sa rokom, nedovoljne dokaze i odbijanje po suštini.", "Ne pretpostavljajte da je odluka obuhvatila tvrdnju koja nikada nije jasno izneta ili dokumentovana."]),
            ("Pregledajte sopstvenu prijavu", ["Proverite da li su datumi, iznosi, traženo rešenje i glavni problem ostali dosledni kroz sve faze spora.", "Povežite svaku važnu tvrdnju sa konkretnim fajlom i zabeležite dokaze koje je Alibaba tražila, ali nije dobila ili razmatrala."]),
            ("Mapirajte preostale opcije", ["Proverite da li su dostupni preispitivanje, žalba, prigovor platnom servisu, osiguranje, formalni zahtev, medijacija, arbitraža ili sud.", "Rokovi i nadležnost zavise od ugovora, pravnog lica, načina plaćanja i mesta; ne oslanjajte se na opšti rok sa interneta."]),
        ],
        "mistakes": ["Brisanje stranica zatvorenog spora", "Pokretanje novog zahteva sa drugačijom nepotkrepljenom pričom", "Izjednačavanje odluke platforme sa sudskom presudom", "Propuštanje bankarskih ili ugovornih rokova dok čekate podršku"],
        "faq": [("Može li zatvoren Alibaba spor ponovo da se otvori?", "Zavisi od statusa, važeće procedure i novih dokaza. Sačuvajte predmet i proverite opcije prikazane na nalogu."), ("Da li zatvaranje znači da je dobavljač dokazano u pravu?", "Ne nužno. Predmet može biti zatvoren iz proceduralnih ili dokaznih razloga. Pročitajte tačan tekst i istoriju."), ("Šta treba da sadrži zahtev za preispitivanje?", "Kratku hronologiju, preciznu grešku, dokaze koji je potvrđuju i jasno traženi ishod.")],
    },
    "customs-clearance-problem": {
        "title": "Roba iz Kine zadržana na carini: kontrolna lista za spor",
        "description": "Kako organizovati dokaze kada je kineska roba zadržana ili odbijena zbog fakture, tarifiranja, sertifikata ili oznaka.",
        "intro": "Carinski problem nije automatski povreda obaveze dobavljača. Najpre utvrdite zvaničan razlog, uvoznika, ugovoreni Incoterm i ko je obećao svaki dokument ili korak usklađenosti.",
        "summary": "Počnite od pisanog obaveštenja carine, pa svaki nedostajući ili netačan podatak povežite sa ugovorom, transportnim dokumentima i odgovornom stranom.",
        "sections": [
            ("Pribavite zvaničan razlog", ["Zatražite obaveštenje carine, špeditera, prevoznika ili organa u kome piše šta nedostaje, nije usklađeno, zabranjeno je ili se proverava.", "Razdvojite običan zahtev za dokument od zadržavanja, zaplene, odbijanja, povrata ili rizika uništenja."]),
            ("Rasporedite odgovornosti", ["Proverite Incoterm, uvoznika, instrukcije špediteru i ugovorna obećanja o tarifiranju, poreklu, vrednosti, sertifikatima i oznakama.", "Ne pretpostavljajte da izraz „od vrata do vrata“ prenosi sve zakonske obaveze bez čitanja pisanog ugovora."]),
            ("Sačuvajte lanac dokumenata", ["Sačuvajte komercijalnu fakturu, packing listu, konosman ili avio-tovarni list, HS kod, dokaze o poreklu, sertifikate, izjave i instrukcije dobavljača.", "Zabeležite svaku ispravljenu verziju i ko ju je izdao da bi trag provere ostao potpun."]),
            ("Kontrolišite troškove i rokove", ["Pratite skladištenje, ležarinu, špeditera, testiranje, povrat i rokove za uništenje uz fakture i obaveštenja.", "Pre nove uplate koju traži dobavljač proverite primaoca i zahtevajte pisano objašnjenje šta uplata rešava."]),
        ],
        "mistakes": ["Oslanjanje samo na objašnjenje dobavljača", "Menjanje fakture bez čuvanja originala", "Ignorisanje rokova skladištenja ili napuštanja robe", "Automatsko okrivljavanje dobavljača bez provere Incoterma"],
        "faq": [("Ko je odgovoran kada carina zaustavi robu?", "Zavisi od zvaničnog razloga, uvoznih propisa, uloge uvoznika, Incoterma i ugovornih obećanja."), ("Da li dobavljač treba da izda novu fakturu?", "Samo kada treba ispraviti stvarnu grešku. Sačuvajte original i ne koristite lažne vrednosti ili opise."), ("Mogu li se carinski troškovi tražiti od dobavljača?", "Moguće je ako ih je izazvala dokumentovana povreda obaveze i ako ugovor ili pravo omogućavaju naknadu.")],
    },
    "damaged-or-short-shipment": {
        "title": "Oštećena ili nepotpuna pošiljka iz Kine: kako dokazati zahtev",
        "description": "Dokazi za oštećene kutije, polomljenu robu, manjak komada, kratku isporuku ili nepotpunu pošiljku kineskog dobavljača.",
        "intro": "Sporovi zbog oštećenja i manjka u velikoj meri zavise od dokaza napravljenih pri prijemu. Fotografisite zatvoreno stanje, etikete, način brojanja i dokumenta prevoznika pre prepakivanja ili distribucije.",
        "summary": "Prikažite ugovorenu količinu, primljenu količinu, stanje pri prijemu, metod kontrole i finansijski efekat manjka ili oštećenja.",
        "sections": [
            ("Dokumentujte stanje pri dolasku", ["Fotografisite kontejner, paletu ili kutije pre otvaranja, uključujući plombe, etikete, udubljenja, vlagu i vidljiva oštećenja.", "Sačuvajte prijemne dokumente i unesite primedbu na oštećenje kod prevoznika."]),
            ("Brojite i uzorkujte sistematski", ["Koristite pisanu listu brojanja sa brojevima kutija, SKU oznakama, serijom i imenom osobe koja je proveravala.", "Za oštećenje navedite koliko je komada pregledano, koliko nije prošlo i kako je uzorak izabran."]),
            ("Razdvojite prevoznika i dobavljača", ["Uporedite obaveze pakovanja, Incoterms, transportna dokumenta i trenutak prelaska rizika.", "Ne pretpostavljajte da je svaki transportni gubitak odgovornost dobavljača niti da je svaki loš paket odgovornost prevoznika."]),
            ("Izračunajte potkrepljen zahtev", ["Povežite svaki nedostajući ili oštećeni komad sa cenom na fakturi i dokazanim troškovima pregleda, popravke ili uništenja.", "Sačuvajte robu i ambalažu dok se ne potvrdi da li je potreban pregled."]),
        ],
        "mistakes": ["Potpisivanje prijema bez primedbe uprkos vidljivom oštećenju", "Bacanje ambalaže pre pregleda", "Tvrdnja da je cela porudžbina neispravna nakon jednog komada", "Traženje paušalnog iznosa bez obračuna"],
        "faq": [("Da li treba otvoriti svaku kutiju?", "Koristite odbranjiv plan pregleda i zabeležite šta je provereno. Obim zavisi od pošiljke i postupka."), ("Ko odgovara za oštećenje u transportu?", "Zavisi od ugovora, Incotermsa, dokumentacije prevoznika, obaveza pakovanja i stvarnog uzroka."), ("Da li pomaže izveštaj skladišta?", "Da, naročito ako beleži vreme prijema, stanje plombi, broj kutija, fotografije i metod pregleda.")],
    },
    "order-not-delivered-tracking-problem": {
        "title": "Porudžbina iz Kine nije dostavljena: praćenje i dokazi",
        "description": "Šta prikupiti kada je broj za praćenje nevažeći, ne menja se, pokazuje pogrešno mesto ili dostavu koju niste primili.",
        "intro": "Nedostavljanje nakon slanja razlikuje se od toga da roba nije poslata. Napravite hronologiju na nivou prevoznika i utvrdite rutu, primaoca, sken dostave i sve izuzetke.",
        "summary": "Sačuvajte ugovorenu adresu, podatke prevoznika, istoriju praćenja, dokaz dostave, prepisku i tačku na kojoj je pošiljka stala ili pogrešno usmerena.",
        "sections": [
            ("Sačuvajte celu istoriju praćenja", ["Sačuvajte naziv prevoznika, ceo broj i sve datirane statuse, a ne samo poslednji.", "Proverite broj u zvaničnom sistemu prevoznika i zabeležite razlike u adresi, težini ili usluzi."]),
            ("Zatražite dokaz dostave", ["Tražite adresu dostave, ime primaoca, potpis, fotografiju, GPS ili zapis lokalnog prevoznika kada postoji.", "Opšti status „dostavljeno“ ne dokazuje da je pravi primalac dobio robu."]),
            ("Pratite sve primopredaje", ["Utvrdite špeditere, konsolidatore, carinske posrednike i poslednju milju, uključujući svaki zamenski broj.", "Zabeležite kada su rizik i odgovornost prešli po ugovoru i Incotermu."]),
            ("Obavestite prave strane", ["Na vreme pisano obavestite prodavca, platformu, prevoznika, osiguravača i platni servis kada je primenljivo.", "Sačuvajte brojeve predmeta i ne bacajte ambalažu ili dokumenta kod delimične dostave."]),
        ],
        "mistakes": ["Korišćenje slike praćenja bez naziva prevoznika", "Propuštanje roka za reklamaciju prevozniku", "Mešanje dostave u posredničko skladište sa dostavom kupcu", "Nečuvanje zamenskih brojeva za praćenje"],
        "faq": [("Praćenje kaže dostavljeno, ali roba nije stigla. Šta sada?", "Zatražite detaljan dokaz i uporedite adresu, primaoca, težinu i lokalni zapis sa porudžbinom."), ("Da li prodavac uvek odgovara za gubitak u transportu?", "Ne. Važni su ugovor, Incoterms, osiguranje i mesto gubitka."), ("Šta ako je broj za praćenje lažan?", "Sačuvajte zvaničan odgovor prevoznika, neslaganja i poruke dobavljača, bez zaključaka šire od dokaza.")],
    },
    "supplier-certificate-problem": {
        "title": "Pogrešan ili nevažeći sertifikat kineskog dobavljača: šta proveriti",
        "description": "Dokazi kada sertifikat nedostaje, odnosi se na drugu robu, ne može da se proveri, istekao je ili nije odgovarajući za tržište.",
        "intro": "Logo ili PDF sa nazivom „sertifikat“ nije dovoljan. Ključno je koji dokument je obećan, ko ga je izdao, koji proizvod i standard pokriva i da li važi za ciljano tržište.",
        "summary": "Uporedite obećani dokument sa izdavaocem, brojem, modelom, standardom, obimom, datumima i zahtevima zemlje odredišta.",
        "sections": [
            ("Sačuvajte šta je obećano", ["Sačuvajte poruke, ponudu i uslov porudžbine u kome piše koji sertifikat, izveštaj, izjava ili registracija treba da budu dostavljeni.", "Zabeležite da li je dokument bio uslov za plaćanje, odobrenje proizvodnje, slanje ili uvoz."]),
            ("Proverite dokument", ["Proverite kontakt izdavaoca, broj, model, podnosioca, proizvođača, standard, datume i javnu bazu ako postoji.", "Kada je važno, kontaktirajte izdavaoca preko podataka pronađenih nezavisno od dobavljača."]),
            ("Razlikujte vrste dokumenata", ["Izveštaj o testu, sertifikat, izjava o usaglašenosti, audit fabrike i registracija proizvoda nisu isto.", "Ne nazivajte dokument falsifikatom bez pouzdanih dokaza; opišite konkretnu nelogičnost ili neuspelu proveru."]),
            ("Povežite sa transakcijom", ["Objasnite zašto nedostajući ili neprikladan dokument sprečava zakonit uvoz, prodaju, ugradnju ili dogovorenu upotrebu.", "Sačuvajte prepisku sa carinom, laboratorijom, konsultantom ili organom koja identifikuje problem."]),
        ],
        "mistakes": ["Prihvatanje sertifikata za drugi model ili proizvođača", "Oslanjanje samo na link dobavljača", "Mešanje izveštaja o testu sa tržišnim odobrenjem", "Optuživanje za falsifikat pre provere"],
        "faq": [("Kako se proverava sertifikat?", "Nezavisno proverite izdavaoca, broj, obim, model i datume. Zahtevi se razlikuju prema proizvodu i tržištu."), ("Da li CE oznaka dokazuje usaglašenost?", "Ne. Sama oznaka ne dokazuje da su ispunjene sve primenljive obaveze i dokumentacija."), ("Može li ovo biti osnov za raskid ili povraćaj?", "Moguće, ako je dokument bio ugovoreni uslov ili roba ne može zakonito da se koristi kako je planirano.")],
    },
    "supplier-disappeared-after-payment": {
        "title": "Kineski dobavljač je nestao posle uplate: prvi koraci",
        "description": "Šta sačuvati i proveriti kada kineski dobavljač prestane da odgovara nakon avansa ili pune uplate.",
        "intro": "Ćutanje nakon uplate može imati više objašnjenja, ali neposredni zadatak je isti: sačuvati dokaze o transakciji, identitetu i komunikaciji pre nego što se nalozi ili stranice promene.",
        "summary": "Zabeležite ko je primio novac, šta je obećano, poslednji potvrđen događaj proizvodnje ili slanja i svaki neuspešan pokušaj kontakta.",
        "sections": [
            ("Sačuvajte identitet i transakciju", ["Sačuvajte naziv firme, registracione podatke, Alibaba ili marketplace profil, sajt, adrese, bankarskog primaoca i fakturu.", "Izvezite ceo razgovor ako je moguće, sa datumima, imenima, prilozima i kontekstom glasovnih poruka."]),
            ("Proverite promene naloga", ["Dokumentujte obrisane oglase, promenu naziva, blokiran nalog, vraćene mejlove i isključene telefone.", "Ne oslanjajte se samo na slike kada postoji izvoz, PDF porudžbine ili bankarski dokument."]),
            ("Koristite kontrolisane kanale", ["Pošaljite jedno jasno pisano obaveštenje preko platforme i ugovorne adrese sa rokom za status ili povraćaj.", "Izbegavajte pretnje i ponovljene emotivne poruke, jer otežavaju pregled hronologije."]),
            ("Zaštitite preostale rokove", ["Odmah proverite rokove platforme, Trade Assurance, kartice, bankarskog transfera, osiguranja i ugovora.", "Molba dobavljača da sačekate ne produžava automatski rok treće strane."]),
        ],
        "mistakes": ["Plaćanje nove naknade za oslobađanje robe ili povraćaja bez provere", "Brisanje razgovora nakon nekoliko slika", "Javno optuživanje nepovezanih lica", "Čekanje nedeljama pre provere rokova"],
        "faq": [("Da li ćutanje dokazuje prevaru?", "Ne. Dokazuje da nema odgovora, ne automatski nameru. Precizno opišite činjenice i sačuvajte uplatu i obećanja."), ("Koji dokument je najvažniji?", "Obično kombinacija porudžbine ili fakture, dokaza o uplati, identiteta dobavljača i poruka o tome šta je trebalo da se dogodi."), ("Da li da objavim podatke dobavljača?", "Javne optužbe mogu stvoriti pravne i praktične rizike. Počnite od čuvanja dokaza i formalnih kanala.")],
    },
    "supplier-not-refunding": {
        "title": "Kineski dobavljač odbija da vrati novac: šta dalje",
        "description": "Praktična lista dokaza i narednih koraka kada kineski dobavljač ili Alibaba prodavac ne vraća avans ili uplatu.",
        "intro": "Obećanje povraćaja nije isto što i primljen novac. Sačuvajte trag plaćanja, osnov otkazivanja ili nedostatka i sve važeće rokove.",
        "summary": "Držite zahtev preciznim: šta je plaćeno, zašto je povraćaj dugovan, šta je prodavac obećao, šta je stvarno vraćeno i koji rok još traje.",
        "sections": [
            ("Potvrdite osnov povraćaja", ["Utvrdite tačan razlog: roba nije poslata, otkazivanje je pisano prihvaćeno, roba je neispravna, specifikacija pogrešna, postoji manjak ili druga dokumentovana povreda.", "Sačuvajte uslove porudžbine i poruku u kojoj dobavljač prihvata otkazivanje, priznaje problem ili obećava povraćaj."]),
            ("Pratite novac", ["Sačuvajte potvrdu uplate, podatke primaoca, zapis platforme, status povraćaja i izvod koji pokazuje da uplata nije stigla.", "Kod delimičnog povraćaja navedite početni iznos, već primljen deo i tačan preostali saldo."]),
            ("Postavite jedan pisani rok", ["Pošaljite kratak zahtev sa brojem porudžbine, iznosom, razlogom, spiskom dokaza, načinom povraćaja i razumnim rokom.", "Ne zamenjujte otvoren postupak beskrajnim privatnim obećanjima i čuvajte rokove platforme, kartice, banke i osiguranja."]),
            ("Pripremite naredni put", ["U zavisnosti od plaćanja i ugovora, mogući su platforma, platni spor, banka, osiguravač, formalni zahtev, medijacija, arbitraža ili sud.", "Ne navodite prevaru kao činjenicu bez dokaza; opišite proverljivo ponašanje."]),
        ],
        "mistakes": ["Zatvaranje spora pre prijema novca", "Slanje dodatnog novca za navodno oslobađanje povraćaja", "Korišćenje različitih iznosa zahteva", "Propuštanje rokova platforme ili platnog servisa"],
        "faq": [("Da li je dovoljna slika obećanja povraćaja?", "Pomaže, ali je spojite sa porudžbinom, uplatom, osnovom povraćaja i bankarskim ili platformskim zapisom da novac nije stigao."), ("Da li da nastavim privatne pregovore?", "Samo dok ne ugrožavaju rok platforme, banke, kartice ili ugovora. Pregovori treba da budu kratki i pisani."), ("Da li ChinaTradeResolve garantuje povraćaj?", "Ne. Servis pomaže da se organizuju činjenice i dokazi, ali ne obećava povraćaj i ne zamenjuje advokata ili organ.")],
    },
    "wrong-material-size-color": {
        "title": "Pogrešan materijal, dimenzija ili boja: kako to dokazati",
        "description": "Kako uporediti odobrenu specifikaciju, uzorak i robu kada materijal, dimenzije, boja ili model ne odgovaraju.",
        "intro": "Zahtev zbog pogrešne specifikacije je najjači kada se može utvrditi konačno odobren zahtev i kada se razlika može izmeriti ili nezavisno proveriti.",
        "summary": "Stavite obećanje i rezultat jedno pored drugog: konačna specifikacija, datum odobrenja, test ili merenje, količina i traženo rešenje.",
        "sections": [
            ("Utvrdite konačnu odobrenu verziju", ["Sačuvajte konačnu porudžbenicu, crteže, kod boje, opis materijala, odobrenje uzorka i kasnije izmene.", "Razrešite protivrečnost između rane poruke i konačne potpisane ili platformske specifikacije."]),
            ("Izmerite neslaganje", ["Koristite kalibrisane alate, reference boja, etikete, laboratoriju ili veštačenje kada problem nije vidljiv.", "Zabeležite metod, datum, identitet uzorka i lanac čuvanja svakog spoljnog testa."]),
            ("Pokažite poslovni značaj", ["Objasnite uticaj na upotrebu, usklađenost, preprodaju, bezbednost, kompatibilnost ili dogovorenu porudžbinu kupca.", "Ne tvrdite da je razlika bitna ako nema dokumentovan efekat na transakciju."]),
            ("Izaberite srazmerno rešenje", ["Navedite da li razlika opravdava zamenu, doradu, sniženje cene, delimičan povraćaj, odbijanje ili otkazivanje.", "Izračunajte iznos iz pogođene količine i dokazanih troškova, a ne kao zaokruženu procenu."]),
        ],
        "mistakes": ["Oslanjanje na boju ekrana za dokaz koda", "Nazivanje materijala lažnim bez testiranja", "Ignorisanje kasnije odobrene izmene", "Nenavođenje broja pogođenih komada"],
        "faq": [("Da li su fotografije dovoljne za pogrešan materijal?", "Ponekad nisu. Sastav često zahteva etikete, priznanje dobavljača, tehničke dokumente ili nezavisan test."), ("Šta ako su uzorak i porudžbenica u suprotnosti?", "Sačuvajte oba i utvrdite koji dokument je prihvaćen kao konačan. Redosled odobrenja je važan."), ("Da li treba testirati svaki komad?", "Ne uvek, ali uzorak mora biti reprezentativan, a metod zabeležen.")],
    },
}
